### ISSUE TITLE
a34380c breaks rephone Lua install

### ISSUE THREAD

**Issue by craigcomstock** [loboris/RePhone_on_Linux#1]
FWIW, this build when Lua is deployed on my RePhone w/ Arduino firmware update doesn't come up. The LED starts blinking blue and the result.txt file says lua.vxp returns 0. If I revert to b005af0 things work fine. I'm happy to help debug the issue and certainly looks like you've made nice improvements to Lua that I'd like to grab from your latest commits.

**Comment by loboris** [comment]
I'm running my RePhone with the firmware included in this repo and I never had any problem.
I'm expecting to finish the basic set of Lua functions/functionality by the end of this week.
Any help, suggestion and bug report is welcome.

**Comment by craigcomstock** [comment]
Once you get your changes in let me know and I'll try it again! Thanks!

```
  From: Boris Lovosevic <notifications@github.com>
```

 To: loboris/RePhone_on_Linux RePhone_on_Linux@noreply.github.com 
Cc: craigcomstock craig_comstock@yahoo.com; Author author@noreply.github.com
 Sent: Thursday, May 5, 2016 3:34 PM
 Subject: Re: [loboris/RePhone_on_Linux] a34380c breaks rephone Lua install (#1)

I'm running my RePhone with the firmware included in this repo and I never had any problem.
I'm expecting to finish the basic set of Lua functions/functionality by the end of this week.
Any help, suggestion and bug report is welcome.—

**Comment by craigcomstock** [comment]
Just built with your master and works fine. Thanks!
