### ISSUE TITLE
semantic of g_shell_result

### ISSUE THREAD

**Issue by andijcr** [loboris/RePhone_on_Linux#3]
hi, i forked your project to add initial support for bluetooth low energy, i started by adding the ble client workflow

what is the semantic of g_shell_result? I'm not sure of what values should i set it to.

**Comment by loboris** [comment]
Some (many) LinkitAssist SDK API's can to be executed from the main thread only. When executing such a function from the lua C function (which is executed in the Lua thread) it is called indirectly via **_remote_CCall()_** function (which sends the _message_ to the main thread and waits for the result). 
**g_shell_result** global variable is used to return the value to the calling function which is mostly the number of parameters returned on Lua stack, but in some cases is used differently.
I'll try to describe the inner working in more details in the documentation when I find some time.
You can analyze some simple examples, e.g. **bt_spp_write()** / **_bt_spp_write()** in **bt.c**

**Comment by andijcr** [comment]
thank you, i'll have a look at that
